name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: '部署环境'
        required: true
        default: 'production'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lab12-final-work
  DOCKER_TAG: latest,${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true  # 安全退出

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            NODE_ENV=production
            COMMIT_SHA=${{ github.sha }}
          # 移除缓存配置（先确保基础推送能工作）
          # cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          # cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max

      - name: Deploy to server
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            docker tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:latest
            docker-compose up -d