name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 优化构建性能

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab12-final-work:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/lab12-final-work:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/lab12-final-work:cache

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 创建项目目录（如果不存在）
            mkdir -p ${{ secrets.PROJECT_PATH || '/var/www/lab12-final-work' }}
            cd ${{ secrets.PROJECT_PATH || '/var/www/lab12-final-work' }}
            
            # 拉取最新代码
            if [ ! -d ".git" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }} .
            else
              git pull origin main
            fi
            
            # 更新并重启容器
            docker-compose pull
            docker-compose up -d --remove-orphans
            
            # 检查部署状态
            echo "部署结果检查:"
            docker-compose ps
            docker images